apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hkvpxegzd-dotnet-basic
  janus-idp.io/tekton: hkvpxegzd-dotnet-basic
  backstage.io/kubernetes-id: hkvpxegzd-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hkvpxegzd-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
